version: "3"

services:
  fivefifthvoter-dev:
    container_name: fivefifthvoter-dev
    build:
      dockerfile: local-development/Dockerfile
      context: ../
    restart: always
    ports:
      - "8539:8539"
    volumes:
      - ../src:/app/src:rw