root: true
env:
  node: true

extends:
  - ".nuxt/.eslint.globals.cjs"
  - "eslint:recommended"
  - "plugin:vue/vue3-recommended"
  - "plugin:prettier-vue/recommended"
globals:
  defineCachedEventHandler: readonly
rules:
  vue/multi-word-component-names: 0
  no-console:
    - error
    - allow:
        - warn
        - error
