# This file is not for deployment. Deployments use S2I builder. This file is for local testing or production builds
# yarn build
# docker build --file=Dockerfile.local -t vuejs/dockerize-vuejs-app .
# docker run -it -P --rm --name test-app-1 vuejs/dockerize-vuejs-app
# docker ps
# open in browser http://localhost:PORT-FROM-PS/
FROM nginx:stable-alpine 
COPY dist /usr/share/nginx/html
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
