on:
  push:
    branches:
      - "**"
  pull_request_target:
    branches:
      - main
name: Check a11y of UI
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    strategy:
      matrix:
        node-version: [14.x]    
    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        run: yarn
      - run: yarn run build
      - run: yarn run test:a11y
      - run: yarn run lint
