on:
  pull_request:
    types: [opened, synchronize, reopened]
name: Build UI
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      #
      # CAUTION: These steps run on code in the PR. They should not execute any code that might be included in the PR.
      # See: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
      #
      - name: Install dependencies
        run: yarn
      - name: Run unit tests
        run: yarn run test:unit
      - name: Checkout code format
        run: yarn ci-format
      - name: Simulate production build
        run: yarn build
