---
name: deploy vNext

on:
  push: # on every push to vNext branch
    branches:
      - vNext
  release: # Execute when a release is created on the vNext branch
    types:
      - created

jobs:
  deploy-vnext:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ui
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install IBM Cloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        shell: bash

      - name: Install Code Engine CLI
        run: ibmcloud plugin install -f code-engine
        shell: bash

      - name: Install Container Registry CLI
        run: ibmcloud plugin install -f container-registry
        shell: bash

      - name: Authenticate with IBM Cloud CLI
        run: ibmcloud login --apikey "${{ secrets.BLUE_IBM_CLOUD_API_KEY }}" -r us-south -g "${{ secrets.BLUE_RESOURCE_GROUP }}"
        shell: bash

      - name: Authenticate with container registry
        run: ibmcloud cr login
        shell: bash

      - name: Select the vNext project
        run: ibmcloud ce project select --name fivefifthsvoter-next
        shell: bash

      - name: Install Yarn
        run: |
          npm install --global yarn
          yarn

      - name: build UI
        run: yarn build

      - name: build services (backend)
        run: |
          cd ../services 
          yarn
          docker build -t fivefifthsvoter-next .

      - name: Push to container registry
        run: |
          DATE_TAG=$(date '+%FT%H%M%S')
          docker tag fivefifthsvoter-next:latest us.icr.io/fivefifthsvoter/fivefifthsvoter-next:latest
          docker tag fivefifthsvoter-next:latest us.icr.io/fivefifthsvoter/fivefifthsvoter-next:$DATE_TAG
          docker push us.icr.io/fivefifthsvoter/fivefifthsvoter-next:latest
          docker push us.icr.io/fivefifthsvoter/fivefifthsvoter-next:$DATE_TAG

      - name: Roll out new version of the app
        run: ibmcloud ce app update -n fivefifthsvoter
        shell: bash

