---
name: deploy

on:
  push: # on every push to main branch
    branches:
      - main
  release: # Execute when a release is created on the master branch
    types:
      - created

jobs:
  deploy-services:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: services
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn test
        run: |
          npm install --global yarn
          yarn
          yarn ci-check

      - name: Configure production
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "production release TBD"

      - name: Configure blue server
        if: ${{ github.event_name == 'push'}}
        run: |
          sed -i  's/"postinstall":.*$/"postinstall": ""/g' package.json
      - name: Install IBM Cloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        shell: bash
      - name: Install Cloud Foundry CLI
        run: ibmcloud cf install
        shell: bash
      - name: Authenticate with IBM Cloud CLI
        run: ibmcloud login --apikey "${{ secrets.BLUE_IBM_CLOUD_API_KEY }}" --no-region -g "${{ secrets.BLUE_RESOURCE_GROUP }}"
        shell: bash
      - name: Target a Cloud Foundry org and space
        run: ibmcloud target --cf-api "${{ secrets.BLUE_IBM_CLOUD_CF_API }}" -o "${{ secrets.BLUE_IBM_CLOUD_CF_ORG }}" -s "${{ secrets.BLUE_IBM_CLOUD_CF_SPACE }}"
        shell: bash
      - name: Deploy to Cloud Foundry
        run: ibmcloud cf push -f manifest-blue.yml --vars-file blue.yml
        shell: bash

  deploy-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ui
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn test
        run: |
          npm install --global yarn
          yarn
          yarn ci-check

      - name: Yarn build
        run: yarn build

      - name: Configure production
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "production release TBD"

      - name: Configure blue server
        if: ${{ github.event_name == 'push'}}
        # see issue https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/issues/306
        run: |
          sed -i  's/"postinstall":.*$/"postinstall": "",/g' package.json

      - name: Deploy UI to IBM Cloud Foundry
        # You may pin to the exact commit or the version.
        uses: IBM/cloudfoundry-deploy@master
        with:
          IBM_CLOUD_API_KEY: ${{ secrets.BLUE_IBM_CLOUD_API_KEY }}
          IBM_CLOUD_CF_API: ${{ secrets.BLUE_IBM_CLOUD_CF_API }}
          IBM_CLOUD_CF_ORG: ${{ secrets.BLUE_IBM_CLOUD_CF_ORG }}
          IBM_CLOUD_CF_SPACE: ${{ secrets.BLUE_IBM_CLOUD_CF_SPACE }}
          RESOURCE_GROUP: ${{ secrets.BLUE_RESOURCE_GROUP }}
          APP_MANIFEST_FILE: ${GITHUB_WORKSPACE}/ui/manifest-blue.yml
          APP_VARS_FILE: ${GITHUB_WORKSPACE}/ui/blue.yml
