on:
  pull_request:
    types: [opened, synchronize, reopened]
name: Test Services
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - name: Install dependencies
        run: yarn
      - name: Run ci-check
        run: yarn ci-check --loglevel debug
